### PR TITLE
feat: header privacy toggle, closes LEA-611

### PR DESCRIPTION
**Pull request by fbwoolf**
Adds the privacy toggle button to the header options and removes the onPress toggle from balances. I also updated the dev console icon to be the `PulseIcon` shown in designs...

### CODE REVIEW

**Review by pete-watters — APPROVED** [review]

**Comment by pete-watters** [comment]
Noticing in the screenshot that the fake news tokens are having a line breaking issue, thats weird

Screenshot 2024-10-17 at 06 16 58

**Review by kyranjamie — APPROVED** [review]
LGTM 

I'm sure these are align centred, but optically they look off to me 
image

**Comment by fabric-8** [comment]
thanks for pointing this out 👁️ 🦅 !

I think the icon is following more of a logic where the eye is supposed to imagine the "bottom line" that is missing, hence it's taking this into consideration for a more psychological/visual centering.

But I agree that it looks a bit off-center next to the other icons — I've made some adjustments to the icon in the design system, [exportable assets should already be updated](https://www.figma.com/design/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?node-id=12599-48048&t=47x8g6n7tVEplFhg-1) ✌️

**Comment by fbwoolf** [comment]
@fabric-8  @kyranjamie fixed, thanks for catching!

IMG_1760
IMG_1762

**Pull request merged**
